FROM eclipse-temurin:17-jre-alpine

COPY ./adobe-common-application/target/jag-adobe-application.jar jag-adobe-application.jar
RUN mkdir ~/.ssh
RUN touch ~/.ssh/known_hosts
RUN chgrp -R 0 ~/.ssh && \
        chmod -R g=u ~/.ssh

ENTRYPOINT ["java","-Xmx1g","-jar","jag-adobe-application.jar"]
