security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}

adobe:
  lifecycle-host: ${LIFECYCLE_HOST}
  ssh:
    username: ${SFEG_USERNAME}
    host: ${SFEG_HOST}
    nfs-dir: ${NFS_DIR}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
