security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}

adobe:
  lifecycle-host: ${LIFECYCLE_HOST}
  webserviceReadTimeout: ${WEBSERVICE_READ_TIMEOUT:600000}

bcgov:
  sftp:
    host: ${SFEG_HOST:localhost}
    port: ${SFEG_PORT:22}
    username: ${SFEG_USERNAME}
    remote-location: ${NFS_DIR}
    known-hosts-file-name: ${SFTP_KNOWN_HOSTS}
    ssh-private-key: ${SFTP_PRIVATE_KEY}

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
