security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}

adobe:
  lifecycle-host: http://127.0.0.1/

bcgov:
  sftp:
    host: http://127.0.0.1/
    port: 22
    username: ${BASIC_AUTH_USER}
    remote-location: /
    known-hosts-file-name: /
    allow-unknown-keys: true
    ssh-private-key: ${SFTP_PRIVATE_KEY}
