security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
adobe:
  lifecycle-host: ${LIFECYCLE_HOST}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

