# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability Scan using Trivy Scanner

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    env:
      BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
      BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
      SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t jag-adobe-common-service:${{ github.sha }} .

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: jag-adobe-common-service:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
