name: ZAP Scanner for Adobe Common Service APIs
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-20.04
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: feature/zapscanner
      
      - name: Update zap properties file
        run: echo  "replacer.full_list(0).replacement=${{ secrets.BASIC_AUTH_HEADER_DEV }}" >> "$GITHUB_WORKSPACE/zapoptions.prop"
      
      - name: ZAP Scan - PDFDiagnostics API
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - PDFDiagnostics API'
          target: '${{ secrets.JAG_AdobeCommonServiceAPI_RouteUrl }}/ws/AdobeCommonServices.Source.CommonServices.ws.provider:PDFDiagnosticsWS?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - PDFTransformationWS API
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - PDFTransformationWS API'
          target: '${{ secrets.JAG_AdobeCommonServiceAPI_RouteUrl }}/ws/AdobeCommonServices.Source.CommonServices.ws.provider:PDFTransformationsWS?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
      
      - name: ZAP Scan - PDFTransformationsSCPWS API
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: soap
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'ZAP Scan Report - PDFTransformationsSCPWS API'
          target: '${{ secrets.JAG_AdobeCommonServiceAPI_RouteUrl }}/ws/AdobeCommonServices.Source.CommonServices.ws.provider:PDFTransformationsSCPWS?WSDL'
          fail_action: true
          cmd_options: '-c "zaprules.conf" -S -z "-configFile /zap/wrk/zapoptions.prop"'
